### PR TITLE
#NoToWar badge & update badges docs

### PR DESCRIPTION
**Pull request by JoJk0**
Added new badge #NoToWar with Russian opposition flag and added it to badges docs alongside with flat version of #StandWithUkraine

### CODE REVIEW

**Comment by webknjaz** [comment]
> Russian opposition flag

I don't believe it's reasonable to host anything russian in this repository. It is also worth noting so-called opposition, while calling out some of the actions of the acting nazi government, still echoes a lot of the propaganda like supporting the annexation of Crimea and the east Ukraine. To an untrained person it may look like they are good folks but they don't support the Ukraine's fight against the fascist terrorists, they just use the situation with the war for their own political advancement.

**Comment by zkochan** [comment]
I completely agree with everything that @webknjaz has written down.

**Comment by cawa-93** [comment]
I think it would be nice to create a badge, or especially a license, etc. with sense "Not for war". I think a lot of open source software and a free license can be used for harassment, espionage, murder and so on. It is a good idea to invite all authors of free licensed programs and libraries to limit the use of their software for military purposes. Maybe not even within this repository

**Comment by Tyrrrz** [comment]
I think while the intent of protesting war is something we can all get behind, the way it's been used in Russia together with the WBW flag is not as straightforward. A lot of individuals who protest war often do it for self-serving purposes (i.e. sanctions) and not necessarily for the sake of Ukraine and its people. Even those with the best intentions often still have skewed or propaganda-influenced perception of reality (e.g. "Ukraine is full of nazis, but war is not the answer"). To that end, I feel it is best that we don't associate that movement directly with the #StandWithUkraine movement.

**Comment by vshymanskyy** [comment]
I mostly agree to above comments

**Pull request closed without merging**
