### PR TITLE
T-Regx supports Ukraine

### PR DESCRIPTION
**Pull request by Danon**
I can't do much with my influence, since T-Regx library doesn't have any kind of UI, I can't add any message without breaking the projects.

I only added your badge to ReadMe: https://github.com/T-Regx/T-Regx/commit/7e4812ab0a0c562c0d3e024926c71c24a98fa3b4 changed my composer description to `Stand with ukraine`.

I have also written a blog post from the template: https://t-regx.com/blog/2022/03/17/stand-with-ukraine

Let's hope russians will see it.

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Thank you!

**Comment by Danon** [comment]
@vshymanskyy Is there anything I can add to the `ReadMe.md` or the the website?

**Comment by Danon** [comment]
@vshymanskyy Like this? https://github.com/T-Regx/T-Regx

**Comment by vshymanskyy** [comment]
Yes. Thanks again!

**Pull request merged**
