### PR TITLE
New #StandWithUkraine badge

### PR DESCRIPTION
**Pull request by vadimdemedes**
What do you think about this badge design? I think the old one wasn't eye-catching and didn't use our flag's colors, which is a missed opportunity, I think.

New badge preserves the same 20px height, so it should align well with other shields.io badges.

Before:

After:

### CODE REVIEW

**Review by artginzburg — CHANGES_REQUESTED** [review]
I think we could do the same thing using the badge generator on [shields.io](https://shields.io), which would look much simpler in code and would be easier to maintain, as the generator is already maintained by shields.io.

Also, if the shields.io idea is not sufficient, the following would consist of much less code changes, though looking almost identical:
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="119" height="20" role="img" aria-label="#StandWithUkraine: 🇺🇦"><title>#StandWithUkraine: 🇺🇦</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="119" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="119" height="20" fill="#ffef8a"/><rect width="119" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="605" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="1090" font-weight="bold">#StandWithUkraine</text><text x="605" y="140" transform="scale(.1)" fill="#2463eb" textLength="1090" font-weight="bold">#StandWithUkraine</text></g></svg>
```

**Comment by cnvoid** [comment]
dont trust USA

**Comment by artginzburg** [comment]
After a recent update, the "Before" version looks sophisticated. The "After" version, anyway, looks toxic: the colors are not quite right. Not to say that subjectively I get a feeling as though someone had installed an old-school porn-banner on my computer.

**Comment by vadimdemedes** [comment]
@artginzburg Not the best place to try to be funny, you're doing a poor attempt at it too.

**Pull request closed without merging**
